import type { Player, Position } from "./types";
import { getPlayerHeadshot } from "./headshots";

// 2026 NFL bye weeks (byes run weeks 5-14; no byes in week 12).
export const BYE_WEEKS: Record<string, number> = {
  CAR: 5,
  KC: 5,
  CIN: 6,
  DET: 6,
  MIA: 6,
  MIN: 6,
  BUF: 7,
  JAX: 7,
  LAC: 7,
  WAS: 7,
  HOU: 8,
  NO: 8,
  NYG: 8,
  SF: 8,
  PIT: 9,
  TEN: 9,
  CHI: 10,
  DEN: 10,
  PHI: 10,
  TB: 10,
  ATL: 11,
  CLE: 11,
  GB: 11,
  LAR: 11,
  NE: 11,
  SEA: 11,
  BAL: 13,
  IND: 13,
  LV: 13,
  NYJ: 13,
  ARI: 14,
  DAL: 14,
};

type PlayerData = readonly [
  name: string,
  position: Position,
  nflTeam: string,
];

const PLAYER_DATA: PlayerData[] = [
  ["Jahmyr Gibbs", "RB", "DET"],
  ["Bijan Robinson", "RB", "ATL"],
  ["Ja'Marr Chase", "WR", "CIN"],
  ["Puka Nacua", "WR", "LAR"],
  ["Jaxon Smith-Njigba", "WR", "SEA"],
  ["Christian McCaffrey", "RB", "SF"],
  ["Amon-Ra St. Brown", "WR", "DET"],
  ["Jonathan Taylor", "RB", "IND"],
  ["James Cook", "RB", "BUF"],
  ["CeeDee Lamb", "WR", "DAL"],
  ["Justin Jefferson", "WR", "MIN"],
  ["Chase Brown", "RB", "CIN"],
  ["De'Von Achane", "RB", "MIA"],
  ["Saquon Barkley", "RB", "PHI"],
  ["Omarion Hampton", "RB", "LAC"],
  ["Kenneth Walker", "RB", "KC"],
  ["Ashton Jeanty", "RB", "LV"],
  ["Drake London", "WR", "ATL"],
  ["Derrick Henry", "RB", "BAL"],
  ["Brock Bowers", "TE", "LV"],
  ["A.J. Brown", "WR", "NE"],
  ["Malik Nabers", "WR", "NYG"],
  ["Nico Collins", "WR", "HOU"],
  ["George Pickens", "WR", "DAL"],
  ["Rashee Rice", "WR", "KC"],
  ["Chris Olave", "WR", "NO"],
  ["Trey McBride", "TE", "ARI"],
  ["DeVonta Smith", "WR", "PHI"],
  ["Breece Hall", "RB", "NYJ"],
  ["Jeremiyah Love", "RB", "ARI"],
  ["Kyren Williams", "RB", "LAR"],
  ["Javonte Williams", "RB", "DAL"],
  ["Zay Flowers", "WR", "BAL"],
  ["Tee Higgins", "WR", "CIN"],
  ["Jaylen Waddle", "WR", "DEN"],
  ["Ladd McConkey", "WR", "LAC"],
  ["Josh Allen", "QB", "BUF"],
  ["Emeka Egbuka", "WR", "TB"],
  ["Colston Loveland", "TE", "CHI"],
  ["Garrett Wilson", "WR", "NYJ"],
  ["Tetairoa McMillan", "WR", "CAR"],
  ["Travis Etienne", "RB", "NO"],
  ["Bucky Irving", "RB", "TB"],
  ["D'Andre Swift", "RB", "CHI"],
  ["Cam Skattebo", "RB", "NYG"],
  ["Bhayshul Tuten", "RB", "JAX"],
  ["Quinshon Judkins", "RB", "CLE"],
  ["David Montgomery", "RB", "HOU"],
  ["Davante Adams", "WR", "LAR"],
  ["Luther Burden", "WR", "CHI"],
  ["Jameson Williams", "WR", "DET"],
  ["Jadarian Price", "RB", "SEA"],
  ["Terry McLaurin", "WR", "WAS"],
  ["Lamar Jackson", "QB", "BAL"],
  ["Rome Odunze", "WR", "CHI"],
  ["Tyler Warren", "TE", "IND"],
  ["Christian Watson", "WR", "GB"],
  ["D.J. Moore", "WR", "BUF"],
  ["TreVeyon Henderson", "RB", "NE"],
  ["Carnell Tate", "WR", "TEN"],
  ["Brian Thomas Jr.", "WR", "JAX"],
  ["Mike Evans", "WR", "SF"],
  ["Marvin Harrison Jr.", "WR", "ARI"],
  ["Parker Washington", "WR", "JAX"],
  ["Jaylen Warren", "RB", "PIT"],
  ["Rhamondre Stevenson", "RB", "NE"],
  ["Drake Maye", "QB", "NE"],
  ["Joe Burrow", "QB", "CIN"],
  ["Jayden Daniels", "QB", "WAS"],
  ["Jonathon Brooks", "RB", "CAR"],
  ["Caleb Williams", "QB", "CHI"],
  ["MarShawn Lloyd", "RB", "GB"],
  ["Tucker Kraft", "TE", "GB"],
  ["Chris Godwin", "WR", "TB"],
  ["Tony Pollard", "RB", "TEN"],
  ["Jalen Hurts", "QB", "PHI"],
  ["Michael Pittman Jr.", "WR", "PIT"],
  ["Jordan Addison", "WR", "MIN"],
  ["DK Metcalf", "WR", "PIT"],
  ["Quentin Johnston", "WR", "LAC"],
  ["Makai Lemon", "WR", "PHI"],
  ["Sam LaPorta", "TE", "DET"],
  ["J.K. Dobbins", "RB", "DEN"],
  ["Rico Dowdle", "RB", "PIT"],
  ["RJ Harvey", "RB", "DEN"],
  ["Courtland Sutton", "WR", "DEN"],
  ["Trevor Lawrence", "QB", "JAX"],
  ["Stefon Diggs", "WR", "WAS"],
  ["Justin Herbert", "QB", "LAC"],
  ["Michael Wilson", "WR", "ARI"],
  ["Jordan Mason", "RB", "MIN"],
  ["Harold Fannin", "TE", "CLE"],
  ["Kyle Pitts", "TE", "ATL"],
  ["Dak Prescott", "QB", "DAL"],
  ["Chuba Hubbard", "RB", "CAR"],
  ["Alec Pierce", "WR", "IND"],
  ["Josh Downs", "WR", "IND"],
  ["Jacory Croskey-Merritt", "RB", "WAS"],
  ["Rachaad White", "RB", "WAS"],
  ["George Kittle", "TE", "SF"],
  ["Wan'Dale Robinson", "WR", "TEN"],
  ["KC Concepcion", "WR", "CLE"],
  ["Blake Corum", "RB", "LAR"],
  ["Matthew Golden", "WR", "GB"],
  ["De'Zhaun Stribling", "WR", "SF"],
  ["Kenneth Gainwell", "RB", "TB"],
  ["Brock Purdy", "QB", "SF"],
  ["Jayden Reed", "WR", "GB"],
  ["Jordyn Tyson", "WR", "NO"],
  ["Bo Nix", "QB", "DEN"],
  ["Jaxson Dart", "QB", "NYG"],
  ["Kyle Monangai", "RB", "CHI"],
  ["Xavier Worthy", "WR", "KC"],
  ["Patrick Mahomes", "QB", "KC"],
  ["Matthew Stafford", "QB", "LAR"],
  ["Deebo Samuel", "WR", "SF"],
  ["Jared Goff", "QB", "DET"],
  ["Aaron Jones", "RB", "MIN"],
  ["Jakobi Meyers", "WR", "JAX"],
  ["Kyler Murray", "QB", "MIN"],
  ["Travis Kelce", "TE", "KC"],
  ["Romeo Doubs", "WR", "NE"],
  ["Jalen Coker", "WR", "CAR"],
  ["Mike Washington Jr.", "RB", "LV"],
  ["Denzel Boston", "WR", "CLE"],
  ["Chris Rodriguez", "RB", "JAX"],
  ["Travis Hunter", "WR", "JAX"],
  ["Jake Ferguson", "TE", "DAL"],
  ["Dalton Kincaid", "TE", "BUF"],
  ["Dallas Goedert", "TE", "PHI"],
  ["Isaiah Likely", "TE", "NYG"],
  ["Woody Marks", "RB", "HOU"],
  ["Keenan Allen", "WR", "IND"],
  ["Baker Mayfield", "QB", "TB"],
  ["Mark Andrews", "TE", "BAL"],
  ["Khalil Shakir", "WR", "BUF"],
  ["Jordan Love", "QB", "GB"],
  ["Jonah Coleman", "RB", "DEN"],
  ["Rashid Shaheed", "WR", "SEA"],
  ["Josh Jacobs", "RB", "GB"],
  ["Tyler Allgeier", "RB", "ARI"],
  ["Tyler Shough", "QB", "NO"],
  ["Malik Willis", "QB", "MIA"],
  ["Keaton Mitchell", "RB", "LAC"],
  ["Tank Bigsby", "RB", "PHI"],
  ["Juwan Johnson", "TE", "NO"],
  ["Jalen McMillan", "WR", "TB"],
  ["Brenton Strange", "TE", "JAX"],
  ["Chigoziem Okonkwo", "TE", "WAS"],
  ["C.J. Stroud", "QB", "HOU"],
  ["Omar Cooper Jr.", "WR", "NYJ"],
  ["Tre Tucker", "WR", "LV"],
  ["Sam Darnold", "QB", "SEA"],
  ["Ja'Kobi Lane", "WR", "BAL"],
  ["Isiah Pacheco", "RB", "DET"],
  ["Cam Ward", "QB", "TEN"],
  ["Hunter Henry", "TE", "NE"],
  ["Dylan Sampson", "RB", "CLE"],
  ["Daniel Jones", "QB", "IND"],
  ["Dalton Schultz", "TE", "HOU"],
  ["Kayshon Boutte", "WR", "NE"],
  ["Tyjae Spears", "RB", "TEN"],
  ["Zach Charbonnet", "RB", "SEA"],
  ["T.J. Hockenson", "TE", "MIN"],
  ["Tyrone Tracy", "RB", "NYG"],
  ["Bryce Young", "QB", "CAR"],
  ["Brian Robinson", "RB", "ATL"],
  ["AJ Barner", "TE", "SEA"],
  ["Kenyon Sadiq", "TE", "NYJ"],
  ["Caleb Douglas", "WR", "MIA"],
  ["Emmett Johnson", "RB", "KC"],
  ["Tre' Harris", "WR", "LAC"],
  ["Oronde Gadsden", "TE", "LAC"],
  ["Alvin Kamara", "RB", "NO"],
  ["Jalen Nailor", "WR", "LV"],
  ["Nicholas Singleton", "RB", "TEN"],
  ["Kaytron Allen", "RB", "WAS"],
  ["Malik Washington", "WR", "MIA"],
  ["Terrance Ferguson", "TE", "LAR"],
  ["Darnell Mooney", "WR", "NYG"],
  ["Antonio Williams", "WR", "WAS"],
  ["Tank Dell", "WR", "HOU"],
  ["Sean Tucker", "RB", "TB"],
  ["Ryan Flournoy", "WR", "DAL"],
  ["Ray Davis", "RB", "BUF"],
  ["Cyrus Allen", "WR", "KC"],
  ["Calvin Ridley", "WR", "TEN"],
  ["Zachariah Branch", "WR", "ATL"],
  ["Demond Claiborne", "RB", "MIN"],
  ["Brandon Aubrey", "K", "DAL"],
  ["Houston Texans", "DST", "HOU"],
  ["Denver Broncos", "DST", "DEN"],
  ["Los Angeles Rams", "DST", "LAR"],
  ["Jason Myers", "K", "SEA"],
  ["Cameron Dicker", "K", "LAC"],
  ["Seattle Seahawks", "DST", "SEA"],
  ["Ka'imi Fairbairn", "K", "HOU"],
  ["Philadelphia Eagles", "DST", "PHI"],
  ["New England Patriots", "DST", "NE"],
  ["Baltimore Ravens", "DST", "BAL"],
  ["Cam Little", "K", "JAX"],
  ["Pittsburgh Steelers", "DST", "PIT"],
  ["Jake Bates", "K", "DET"],
  ["Detroit Lions", "DST", "DET"],
  ["Eddy Pineiro", "K", "SF"],
  ["Harrison Mevis", "K", "LAR"],
  ["Los Angeles Chargers", "DST", "LAC"],
  ["Will Reichard", "K", "MIN"],
  ["Tyler Loop", "K", "BAL"],
  ["Jacksonville Jaguars", "DST", "JAX"],
  ["Minnesota Vikings", "DST", "MIN"],
  ["Harrison Butker", "K", "KC"],
  ["Evan McPherson", "K", "CIN"],
  ["Kansas City Chiefs", "DST", "KC"],
  ["Green Bay Packers", "DST", "GB"],
  ["Cairo Santos", "K", "CHI"],
  ["Chris Boswell", "K", "PIT"],
  ["Jayden Higgins", "WR", "HOU"],
];

export const PLAYERS: Player[] = PLAYER_DATA.map(
  ([name, position, nflTeam], index) => {
    const rank = index + 1;

    return {
      id: rank,
      rank,
      name,
      position,
      nflTeam,
      bye: BYE_WEEKS[nflTeam],
      headshot: getPlayerHeadshot(name, position, nflTeam),
    };
  },
);
